// Date: 2014-7-31 鏄熸湡鍥�14:17:34
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.frostcraftsman.gimmickery.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelKarakuriNingyG extends ModelBase
{
  //fields
    ModelRenderer Left_Leg;
    ModelRenderer Right_Leg;
    ModelRenderer left_Leg_sock_left;
    ModelRenderer Left_Leg_sock_right;
    ModelRenderer Left_Leg_sock_Front;
    ModelRenderer Left_Leg_sock_back;
    ModelRenderer Right_Leg_sock_left;
    ModelRenderer Right_Leg_sock_right;
    ModelRenderer Right_Leg_sock_front;
    ModelRenderer Right_Leg_sock_back;
    ModelRenderer Body;
    ModelRenderer neck;
    ModelRenderer collar_left;
    ModelRenderer collar_right;
    ModelRenderer collar_back;
    ModelRenderer head;
    ModelRenderer left_hair;
    ModelRenderer right_hair;
    ModelRenderer Front_hair;
    ModelRenderer Front_hair_medium;
    ModelRenderer Front_hair_right;
    ModelRenderer back_hair;
    ModelRenderer top_hair;
    ModelRenderer front_hair1;
    ModelRenderer front_hair_2;
    ModelRenderer front_hair3;
    ModelRenderer front_hair_4;
    ModelRenderer front_hair5;
    ModelRenderer front_hair6;
    ModelRenderer front_hair7;
    ModelRenderer outer_left_hair;
    ModelRenderer outer_right_hair;
    ModelRenderer back_hair1;
    ModelRenderer back_hair2;
    ModelRenderer back_hair3;
    ModelRenderer back_hair4;
    ModelRenderer back_hair5;
    ModelRenderer left_arm;
    ModelRenderer right_arm;
    ModelRenderer left_sleeve;
    ModelRenderer outter_left_sleeve;
    ModelRenderer outtest_left_sleeve;
    ModelRenderer right_sleeve;
    ModelRenderer outter_right_sleeve;
    ModelRenderer outtest_right_sleeve;
    ModelRenderer tie1;
    ModelRenderer tie3;
    ModelRenderer tie4;
    ModelRenderer tie5;
    ModelRenderer pang_ci1;
    ModelRenderer pang_ci2;
    ModelRenderer pang_ci3;
    ModelRenderer left_skirt;
    ModelRenderer left_side_skirt_1;
    ModelRenderer left_side_skirt_2;
    ModelRenderer right_skirt;
    ModelRenderer right_side_skirt_1;
    ModelRenderer right_side_skirt_2;
    ModelRenderer front_skirt;
    ModelRenderer front_side_skirt1;
    ModelRenderer front_side_skirt_2;
    ModelRenderer back_skirt;
    ModelRenderer back_side_skirt1;
    ModelRenderer back_side_skirt2;
    ModelRenderer left_sock_bottom;
    ModelRenderer right_sock_bottom;
    ModelRenderer clothes_right_bottom1;
    ModelRenderer clothes_right_bottom2;
    ModelRenderer clothes_right_bottom3;
    ModelRenderer clothes_right_bottom4;
    ModelRenderer clothes_left_bottom1;
    ModelRenderer clothes_left_bottom2;
    ModelRenderer clothes_left_bottom3;
    ModelRenderer clothes_left_bottom4;
    ModelRenderer left_hand_front_lace;
    ModelRenderer left_hand_back_lace;
    ModelRenderer left_hand_left_lace;
    ModelRenderer lfet_hand_right_lace;
    ModelRenderer right_hand_front_lace;
    ModelRenderer right_hand_back_lace;
    ModelRenderer right_hand_right_lace;
    ModelRenderer right_hand_left_lace;
    ModelRenderer left_hand_front_fronter_lace1;
    ModelRenderer left_hand_front_fronter_lace2;
    ModelRenderer left_hand_front_fronter_lace3;
    ModelRenderer left_hand_right_fronter_lace1;
    ModelRenderer left_hand_right_fronter_lace2;
    ModelRenderer left_hand_right_fronter_lace3;
    ModelRenderer left_hand_right_fronter_lace4;
    ModelRenderer left_hand_back_fronter_lace1;
    ModelRenderer left_hand_back_fronter_lace2;
    ModelRenderer Left_hand_back_fronter_lace3;
    ModelRenderer left_hand_back_fronter_lace4;
    ModelRenderer Left_hand_left_fronter_lace1;
    ModelRenderer left_hand_left_fronter_lace2;
    ModelRenderer left_hand_left_fronter_lace3;
    ModelRenderer right_hand_front_fronter_lace1;
    ModelRenderer right_hand_front_fronter_lace2;
    ModelRenderer right_hand_front_fronter_lace3;
    ModelRenderer right_hand_front_fronter_lace4;
    ModelRenderer right_hand_right_fronter_lace1;
    ModelRenderer right_hand_right_fronter_lace2;
    ModelRenderer right_hand_right_fronter_lace3;
    ModelRenderer right_hand_right_fronter_lace4;
    ModelRenderer right_hand_back_fronter_lace1;
    ModelRenderer right_hand_back_fronter_lace2;
    ModelRenderer right_hand_back_fronter_lace3;
    ModelRenderer right_hand_left_fronter_lace1;
    ModelRenderer right_hand_left_fronter_lace2;
    ModelRenderer right_hand_left_fronter_lace3;
    ModelRenderer outer_left_hair1;
    ModelRenderer outer_left_hair2;
    ModelRenderer outer_left_hair3;
    ModelRenderer outer_left_hair4;
    ModelRenderer outer_right_hair1;
    ModelRenderer outer_right_hair2;
    ModelRenderer outer_right_hair3;
    ModelRenderer outer_right_hair4;
    ModelRenderer upper_left_arm;
    ModelRenderer left_arm_long_sleeve_front;
    ModelRenderer Left_arm_long_sleeve_bottom;
    ModelRenderer left_arm_long_sleeve_left;
    ModelRenderer left_arm_long_sleeve_back;
    ModelRenderer upper_right_arm_;
    ModelRenderer right_arm_long_sleeve_front;
    ModelRenderer right_arm_long_sleeve_bottom;
    ModelRenderer right_arm_long_sleeve_left;
    ModelRenderer right_arm_long_sleeve_back;
  
  public ModelKarakuriNingyG()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Left_Leg = new ModelRenderer(this, 0, 22);//
      Left_Leg.addBox(-3F, -1F, -1F, 2, 16, 2);
      Left_Leg.setRotationPoint(-1F, 9F, 1F);
      Left_Leg.setTextureSize(256, 128);
      Left_Leg.mirror = true;
      setRotation(Left_Leg, 0F, 0F, 0F);
      Right_Leg = new ModelRenderer(this, 0, 2);//
      Right_Leg.addBox(1F, -1F, -1F, 2, 16, 2);
      Right_Leg.setRotationPoint(1F, 9F, 1F);
      Right_Leg.setTextureSize(256, 128);
      Right_Leg.mirror = true;
      setRotation(Right_Leg, 0F, 0F, 0F);
      left_Leg_sock_left = new ModelRenderer(this, 0, 70);//
      left_Leg_sock_left.addBox(-4F, 4F, -1F, 1, 11, 2);
      left_Leg_sock_left.setRotationPoint(-1F, 9F, 1F);
      left_Leg_sock_left.setTextureSize(256, 128);
      left_Leg_sock_left.mirror = true;
      setRotation(left_Leg_sock_left, 0F, 0F, 0F);
      Left_Leg_sock_right = new ModelRenderer(this, 0, 56);//
      Left_Leg_sock_right.addBox(-1F, 4F, -1F, 1, 11, 2);
      Left_Leg_sock_right.setRotationPoint(-1F, 9F, 1F);
      Left_Leg_sock_right.setTextureSize(256, 128);
      Left_Leg_sock_right.mirror = true;
      setRotation(Left_Leg_sock_right, 0F, 0F, 0F);
      Left_Leg_sock_Front = new ModelRenderer(this, 0, 42);//
      Left_Leg_sock_Front.addBox(-4F, 4F, -2F, 4, 11, 1);
      Left_Leg_sock_Front.setRotationPoint(-1F, 9F, 1F);
      Left_Leg_sock_Front.setTextureSize(256, 128);
      Left_Leg_sock_Front.mirror = true;
      setRotation(Left_Leg_sock_Front, 0F, 0F, 0F);
      Left_Leg_sock_back = new ModelRenderer(this, 0, 42);//
      Left_Leg_sock_back.addBox(-4F, 4F, 1F, 4, 11, 1);
      Left_Leg_sock_back.setRotationPoint(-1F, 9F, 1F);
      Left_Leg_sock_back.setTextureSize(256, 128);
      Left_Leg_sock_back.mirror = true;
      setRotation(Left_Leg_sock_back, 0F, 0F, 0F);
      Right_Leg_sock_left = new ModelRenderer(this, 0, 56);//
      Right_Leg_sock_left.addBox(0F, 4F, -1F, 1, 11, 2);
      Right_Leg_sock_left.setRotationPoint(1F, 9F, 1F);
      Right_Leg_sock_left.setTextureSize(256, 128);
      Right_Leg_sock_left.mirror = true;
      setRotation(Right_Leg_sock_left, 0F, 0F, 0F);
      Right_Leg_sock_right = new ModelRenderer(this, 0, 70);//
      Right_Leg_sock_right.addBox(3F, 4F, -1F, 1, 11, 2);
      Right_Leg_sock_right.setRotationPoint(1F, 9F, 1F);
      Right_Leg_sock_right.setTextureSize(256, 128);
      Right_Leg_sock_right.mirror = true;
      setRotation(Right_Leg_sock_right, 0F, 0F, 0F);
      Right_Leg_sock_front = new ModelRenderer(this, 0, 42);//
      Right_Leg_sock_front.addBox(0F, 4F, -2F, 4, 11, 1);
      Right_Leg_sock_front.setRotationPoint(1F, 9F, 1F);
      Right_Leg_sock_front.setTextureSize(256, 128);
      Right_Leg_sock_front.mirror = true;
      setRotation(Right_Leg_sock_front, 0F, 0F, 0F);
      Right_Leg_sock_back = new ModelRenderer(this, 0, 42);//
      Right_Leg_sock_back.addBox(0F, 4F, 1F, 4, 11, 1);
      Right_Leg_sock_back.setRotationPoint(1F, 9F, 1F);
      Right_Leg_sock_back.setTextureSize(256, 128);
      Right_Leg_sock_back.mirror = true;
      setRotation(Right_Leg_sock_back, 0F, 0F, 0F);
      
      Left_Leg.addChild(left_Leg_sock_left);
      Left_Leg.addChild(Left_Leg_sock_right);
      Left_Leg.addChild(Left_Leg_sock_back);
      Left_Leg.addChild(Left_Leg_sock_Front);
      
      Right_Leg.addChild(Right_Leg_sock_left);
      Right_Leg.addChild(Right_Leg_sock_right);
      Right_Leg.addChild(Right_Leg_sock_front);
      Right_Leg.addChild(Right_Leg_sock_back);
      
      Body = new ModelRenderer(this, 16, 75);
      Body.addBox(0F, 0F, 0F, 10, 15, 6);
      Body.setRotationPoint(-5F, -8F, -2F);
      Body.setTextureSize(256, 128);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      neck = new ModelRenderer(this, 183, 66);//
      neck.addBox(-1.5F, -1F, -1F, 3, 2, 2);
      neck.setRotationPoint(0F, -9F, 1F);
      neck.setTextureSize(256, 128);
      neck.mirror = true;
      setRotation(neck, 0F, 0F, 0F);
      collar_left = new ModelRenderer(this, 170, 74);
      collar_left.addBox(0F, 0F, 0F, 3, 1, 5);
      collar_left.setRotationPoint(-4.5F, -9F, -3F);
      collar_left.setTextureSize(256, 128);
      collar_left.mirror = true;
      setRotation(collar_left, 0F, 0F, 0F);
      collar_right = new ModelRenderer(this, 190, 74);
      collar_right.addBox(0F, 0F, 0F, 3, 1, 5);
      collar_right.setRotationPoint(1.5F, -9F, -3F);
      collar_right.setTextureSize(256, 128);
      collar_right.mirror = true;
      setRotation(collar_right, 0F, 0F, 0F);
      collar_back = new ModelRenderer(this, 177, 83);
      collar_back.addBox(0F, 0F, 0F, 9, 1, 2);
      collar_back.setRotationPoint(-4.5F, -9F, 2F);
      collar_back.setTextureSize(256, 128);
      collar_back.mirror = true;
      setRotation(collar_back, 0F, 0F, 0F);
      head = new ModelRenderer(this, 172, 45);//
      head.addBox(-4F, -8.5F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, -9F, 1F);
      head.setTextureSize(256, 128);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      left_hair = new ModelRenderer(this, 133, 23);//
      left_hair.addBox(-5F, -9F, -4F, 1, 7, 7);
      left_hair.setRotationPoint(0F, -9F, 1F);
      left_hair.setTextureSize(256, 128);
      left_hair.mirror = true;
      setRotation(left_hair, 0F, 0F, 0F);
      right_hair = new ModelRenderer(this, 224, 22);//
      right_hair.addBox(4F, -9F, -4F, 1, 7, 7);
      right_hair.setRotationPoint(0F, -9F, 1F);
      right_hair.setTextureSize(256, 128);
      right_hair.mirror = true;
      setRotation(right_hair, 0F, 0F, 0F);
      Front_hair = new ModelRenderer(this, 175, 37);//
      Front_hair.addBox(-3F, -10F, -5.5F, 2, 3, 1);
      Front_hair.setRotationPoint(0F, -9F, 1F);
      Front_hair.setTextureSize(256, 128);
      Front_hair.mirror = true;
      setRotation(Front_hair, 0F, 0F, 0F);
      Front_hair_medium = new ModelRenderer(this, 184, 37);//
      Front_hair_medium.addBox(-1F, -10F, -6F, 2, 4, 1);
      Front_hair_medium.setRotationPoint(0F, -9F, 1F);
      Front_hair_medium.setTextureSize(256, 128);
      Front_hair_medium.mirror = true;
      setRotation(Front_hair_medium, 0F, 0F, 0F);
      Front_hair_right = new ModelRenderer(this, 193, 37);//
      Front_hair_right.addBox(1F, -10F, -5.5F, 2, 3, 1);
      Front_hair_right.setRotationPoint(0F, -9F, 1F);
      Front_hair_right.setTextureSize(256, 128);
      Front_hair_right.mirror = true;
      setRotation(Front_hair_right, 0F, 0F, 0F);
      back_hair = new ModelRenderer(this, 189, 5);//
      back_hair.addBox(-2F, -9F, 4F, 1, 8, 1);
      back_hair.setRotationPoint(0F, -9F, 1F);
      back_hair.setTextureSize(256, 128);
      back_hair.mirror = true;
      setRotation(back_hair, 0F, 0F, 0F);
      top_hair = new ModelRenderer(this, 170, 21);//
      top_hair.addBox(-4F, -9.5F, -5F, 8, 1, 8);
      top_hair.setRotationPoint(0F, -9F, 1F);
      top_hair.setTextureSize(256, 128);
      top_hair.mirror = true;
      setRotation(top_hair, 0F, 0F, 0F);
      front_hair1 = new ModelRenderer(this, 154, 40);//
      front_hair1.addBox(-6F, -8F, -5F, 1, 2, 1);
      front_hair1.setRotationPoint(0F, -9F, 1F);
      front_hair1.setTextureSize(256, 128);
      front_hair1.mirror = true;
      setRotation(front_hair1, 0F, 0F, 0F);
      front_hair_2 = new ModelRenderer(this, 161, 38);//
      front_hair_2.addBox(-5F, -9F, -5F, 1, 4, 1);
      front_hair_2.setRotationPoint(0F, -9F, 1F);
      front_hair_2.setTextureSize(256, 128);
      front_hair_2.mirror = true;
      setRotation(front_hair_2, 0F, 0F, 0F);
      front_hair3 = new ModelRenderer(this, 168, 36);//
      front_hair3.addBox(-4F, -10F, -5F, 1, 6, 1);
      front_hair3.setRotationPoint(0F, -8.7F, 1F);
      front_hair3.setTextureSize(256, 128);
      front_hair3.mirror = true;
      setRotation(front_hair3, 0F, 0F, 0F);
      front_hair_4 = new ModelRenderer(this, 179, 33);//
      front_hair_4.addBox(-3F, -10F, -5F, 6, 1, 1);
      front_hair_4.setRotationPoint(0F, -9F, 1F);
      front_hair_4.setTextureSize(256, 128);
      front_hair_4.mirror = true;
      setRotation(front_hair_4, 0F, 0F, 0F);
      front_hair5 = new ModelRenderer(this, 201, 35);//
      front_hair5.addBox(3F, -10F, -5F, 1, 6, 1);
      front_hair5.setRotationPoint(0F, -8.7F, 1F);
      front_hair5.setTextureSize(256, 128);
      front_hair5.mirror = true;
      setRotation(front_hair5, 0F, 0F, 0F);
      front_hair6 = new ModelRenderer(this, 207, 37);//
      front_hair6.addBox(4F, -9F, -5F, 1, 4, 1);
      front_hair6.setRotationPoint(0F, -9F, 1F);
      front_hair6.setTextureSize(256, 128);
      front_hair6.mirror = true;
      setRotation(front_hair6, 0F, 0F, 0F);
      front_hair7 = new ModelRenderer(this, 213, 39);//
      front_hair7.addBox(5F, -8F, -5F, 1, 2, 1);
      front_hair7.setRotationPoint(0F, -9F, 1F);
      front_hair7.setTextureSize(256, 128);
      front_hair7.mirror = true;
      setRotation(front_hair7, 0F, 0F, 0F);
      
      Front_hair.addChild(front_hair_2);
      Front_hair.addChild(front_hair3);
      Front_hair.addChild(front_hair_4);
      Front_hair.addChild(front_hair5);
      Front_hair.addChild(front_hair6);
      Front_hair.addChild(front_hair7);
      Front_hair.addChild(front_hair1);
      Front_hair.addChild(Front_hair_medium);
      Front_hair.addChild(Front_hair_right );
      
      head.addChild(Front_hair);
      head.addChild(top_hair);
      head.addChild(back_hair);
      head.addChild(right_hair);
      head.addChild(left_hair);
      head.addChild(neck);
      head.addChild(outer_left_hair);
      head.addChild(outer_right_hair);
      head.addChild(outer_left_hair1);
      head.addChild(outer_left_hair2);
      head.addChild(outer_left_hair3);
      head.addChild(outer_left_hair4);
      head.addChild(outer_right_hair1);
      head.addChild(outer_right_hair2);
      head.addChild(outer_right_hair3);
      head.addChild(outer_right_hair4);
      
      outer_left_hair1 = new ModelRenderer(this, 148, 45);//
      outer_left_hair1.addBox(-6F, -8F, -3F, 1, 8, 1);
      outer_left_hair1.setRotationPoint(0F, -9F, 1F);
      outer_left_hair1.setTextureSize(256, 128);
      outer_left_hair1.mirror = true;
      setRotation(outer_left_hair1, 0F, 0F, 0F);
      outer_left_hair2 = new ModelRenderer(this, 142, 45);//
      outer_left_hair2.addBox(-6F, -8F, -2F, 1, 7, 1);
      outer_left_hair2.setRotationPoint(0F, -9F, 1F);
      outer_left_hair2.setTextureSize(256, 128);
      outer_left_hair2.mirror = true;
      setRotation(outer_left_hair2, 0F, 0F, 0F);
      outer_left_hair3 = new ModelRenderer(this, 135, 45);//
      outer_left_hair3.addBox(-6F, -8F, -1F, 1, 6, 1);
      outer_left_hair3.setRotationPoint(0F, -9F, 1F);
      outer_left_hair3.setTextureSize(256, 128);
      outer_left_hair3.mirror = true;
      setRotation(outer_left_hair3, 0F, 0F, 0F);
      outer_left_hair4 = new ModelRenderer(this, 127, 44);//
      outer_left_hair4.addBox(-6F, -8F, 0F, 1, 6, 2);
      outer_left_hair4.setRotationPoint(0F, -9F, 1F);
      outer_left_hair4.setTextureSize(256, 128);
      outer_left_hair4.mirror = true;
      setRotation(outer_left_hair4, 0F, 0F, 0F);
      outer_right_hair1 = new ModelRenderer(this, 224, 46);//
      outer_right_hair1.addBox(5F, -8F, -3F, 1, 8, 1);
      outer_right_hair1.setRotationPoint(0F, -9F, 1F);
      outer_right_hair1.setTextureSize(256, 128);
      outer_right_hair1.mirror = true;
      setRotation(outer_right_hair1, 0F, 0F, 0F);
      outer_right_hair2 = new ModelRenderer(this, 230, 46);//
      outer_right_hair2.addBox(5F, -8F, -2F, 1, 7, 1);
      outer_right_hair2.setRotationPoint(0F, -9F, 1F);
      outer_right_hair2.setTextureSize(256, 128);
      outer_right_hair2.mirror = true;
      setRotation(outer_right_hair2, 0F, 0F, 0F);
      outer_right_hair3 = new ModelRenderer(this, 237, 46);//
      outer_right_hair3.addBox(5F, -8F, -1F, 1, 6, 1);
      outer_right_hair3.setRotationPoint(0F, -9F, 1F);
      outer_right_hair3.setTextureSize(256, 128);
      outer_right_hair3.mirror = true;
      setRotation(outer_right_hair3, 0F, 0F, 0F);
      outer_right_hair4 = new ModelRenderer(this, 243, 46);//
      outer_right_hair4.addBox(5F, -8F, 0F, 1, 6, 2);
      outer_right_hair4.setRotationPoint(0F, -9F, 1F);
      outer_right_hair4.setTextureSize(256, 128);
      outer_right_hair4.mirror = true;
      setRotation(outer_right_hair4, 0F, 0F, 0F);
      outer_left_hair = new ModelRenderer(this, 154, 45);//
      outer_left_hair.addBox(-6F, -8F, -4F, 1, 9, 1);
      outer_left_hair.setRotationPoint(0F, -9F, 1F);
      outer_left_hair.setTextureSize(256, 128);
      outer_left_hair.mirror = true;
      setRotation(outer_left_hair, 0F, 0F, 0F);
      outer_right_hair = new ModelRenderer(this, 219, 46);//
      outer_right_hair.addBox(5F, -8F, -4F, 1, 9, 1);
      outer_right_hair.setRotationPoint(0F, -9F, 1F);
      outer_right_hair.setTextureSize(256, 128);
      outer_right_hair.mirror = true;
      setRotation(outer_right_hair, 0F, 0F, 0F);
      back_hair1 = new ModelRenderer(this, 163, 5);//
      back_hair1.addBox(2F, -9F, 4F, 2, 7, 1);
      back_hair1.setRotationPoint(0F, -9F, 1F);
      back_hair1.setTextureSize(256, 128);
      back_hair1.mirror = true;
      setRotation(back_hair1, 0F, 0F, 0F);
      back_hair2 = new ModelRenderer(this, 171, 5);//
      back_hair2.addBox(1F, -9F, 4F, 1, 8, 1);
      back_hair2.setRotationPoint(0F, -9F, 1F);
      back_hair2.setTextureSize(256, 128);
      back_hair2.mirror = true;
      setRotation(back_hair2, 0F, 0F, 0F);
      back_hair3 = new ModelRenderer(this, 177, 5);//
      back_hair3.addBox(0F, -9F, 4F, 1, 9, 1);
      back_hair3.setRotationPoint(0F, -9F, 1F);
      back_hair3.setTextureSize(256, 128);
      back_hair3.mirror = true;
      setRotation(back_hair3, 0F, 0F, 0F);
      back_hair4 = new ModelRenderer(this, 183, 5);//
      back_hair4.addBox(-1F, -9F, 4F, 1, 9, 1);
      back_hair4.setRotationPoint(0F, -9F, 1F);
      back_hair4.setTextureSize(256, 128);
      back_hair4.mirror = true;
      setRotation(back_hair4, 0F, 0F, 0F);
      back_hair5 = new ModelRenderer(this, 195, 5);//
      back_hair5.addBox(-4F, -9F, 4F, 2, 7, 1);
      back_hair5.setRotationPoint(0F, -9F, 1F);
      back_hair5.setTextureSize(256, 128);
      back_hair5.mirror = true;
      setRotation(back_hair5, 0F, 0F, 0F);
      
      back_hair.addChild(back_hair1);
      back_hair.addChild(back_hair2);
      back_hair.addChild(back_hair3);
      back_hair.addChild(back_hair4);
      back_hair.addChild(back_hair5);
      
      left_arm = new ModelRenderer(this, 65, 0);//
      left_arm.addBox(-1F, -2F, -2F, 1, 7, 4);
      left_arm.setRotationPoint(-5F, -6F, 1F);
      left_arm.setTextureSize(256, 128);
      left_arm.mirror = true;
      setRotation(left_arm, 0F, 0F, 0F);   
      right_arm = new ModelRenderer(this, 102, 0);//
      right_arm.addBox(0F, -2F, -2F, 1, 7, 4);
      right_arm.setRotationPoint(5F, -6F, 1F);
      right_arm.setTextureSize(256, 128);
      right_arm.mirror = true;
      setRotation(right_arm, 0F, 0F, 0F);
      left_sleeve = new ModelRenderer(this, 63, 15);//
      left_sleeve.addBox(-5F, 5F, -3F, 6, 11, 6);
      left_sleeve.setRotationPoint(-5F, -6F, 1F);
      left_sleeve.setTextureSize(256, 128);
      left_sleeve.mirror = true;
      setRotation(left_sleeve, 0F, 0F, 0F);
      outter_left_sleeve = new ModelRenderer(this, 63, 34);//
      outter_left_sleeve.addBox(-5F, 8F, 3F, 6, 8, 2);
      outter_left_sleeve.setRotationPoint(-5F, -6F, 1F);
      outter_left_sleeve.setTextureSize(256, 128);
      outter_left_sleeve.mirror = true;
      setRotation(outter_left_sleeve, 0F, 0F, 0F);
      outtest_left_sleeve = new ModelRenderer(this, 63, 47);//
      outtest_left_sleeve.addBox(-5F, 11F, 5F, 6, 5, 1);
      outtest_left_sleeve.setRotationPoint(-5F, -6F, 1F);
      outtest_left_sleeve.setTextureSize(256, 128);
      outtest_left_sleeve.mirror = true;
      setRotation(outtest_left_sleeve, 0F, 0F, 0F);
      right_sleeve = new ModelRenderer(this, 102, 15);//
      right_sleeve.addBox(-1F, 5F, -3F, 6, 11, 6);
      right_sleeve.setRotationPoint(5F, -6F, 1F);
      right_sleeve.setTextureSize(256, 128);
      right_sleeve.mirror = true;
      setRotation(right_sleeve, 0F, 0F, 0F);
      outter_right_sleeve = new ModelRenderer(this, 102, 35);//
      outter_right_sleeve.addBox(-1F, 8F, 3F, 6, 8, 2);
      outter_right_sleeve.setRotationPoint(5F, -6F, 1F);
      outter_right_sleeve.setTextureSize(256, 128);
      outter_right_sleeve.mirror = true;
      setRotation(outter_right_sleeve, 0F, 0F, 0F);
      outtest_right_sleeve = new ModelRenderer(this, 102, 47);//
      outtest_right_sleeve.addBox(-1F, 11F, 5F, 6, 5, 1);
      outtest_right_sleeve.setRotationPoint(5F, -6F, 1F);
      outtest_right_sleeve.setTextureSize(256, 128);
      outtest_right_sleeve.mirror = true;
      setRotation(outtest_right_sleeve, 0F, 0F, 0F);
      
      tie1.addChild(tie3); 
      tie1.addChild(tie4);
      tie1.addChild(tie5);
      
      tie1 = new ModelRenderer(this, 29, 100);//
      tie1.addBox(-1F, 0F, -2F, 2, 3, 1);
      tie1.setRotationPoint(0F, -9F, -1F);
      tie1.setTextureSize(256, 128);
      tie1.mirror = true;
      setRotation(tie1, 0F, 0F, 0F);
      tie3 = new ModelRenderer(this, 28, 105);//
      tie3.addBox(-1.5F, 3F, -2.5F, 3, 3, 1);
      tie3.setRotationPoint(0F, -9F, -1F);
      tie3.setTextureSize(256, 128);
      tie3.mirror = true;
      setRotation(tie3, 0F, 0F, 0F);
      tie4 = new ModelRenderer(this, 27, 110);//
      tie4.addBox(-2F, 6F, -3F, 4, 2, 1);
      tie4.setRotationPoint(0F, -9F, -1F);
      tie4.setTextureSize(256, 128);
      tie4.mirror = true;
      setRotation(tie4, 0F, 0F, 0F);
      tie5 = new ModelRenderer(this, 29, 115);//
      tie5.addBox(-1F, 8F, -2F, 2, 2, 1);
      tie5.setRotationPoint(0F, -9F, -1.5F);
      tie5.setTextureSize(256, 128);
      tie5.mirror = true;
      setRotation(tie5, 0F, 0F, 0F);
      pang_ci1 = new ModelRenderer(this, 22, 41);
      pang_ci1.addBox(0F, 0F, 0F, 8, 1, 2);
      pang_ci1.setRotationPoint(-4F, 7F, 0F);
      pang_ci1.setTextureSize(256, 128);
      pang_ci1.mirror = true;
      setRotation(pang_ci1, 0F, 0F, 0F);
      pang_ci2 = new ModelRenderer(this, 24, 46);
      pang_ci2.addBox(0F, 0F, 0F, 6, 1, 2);
      pang_ci2.setRotationPoint(-3F, 8F, 0F);
      pang_ci2.setTextureSize(256, 128);
      pang_ci2.mirror = true;
      setRotation(pang_ci2, 0F, 0F, 0F);
      pang_ci3 = new ModelRenderer(this, 26, 51);
      pang_ci3.addBox(0F, 0F, 0F, 4, 1, 2);
      pang_ci3.setRotationPoint(-2F, 9F, 0F);
      pang_ci3.setTextureSize(256, 128);
      pang_ci3.mirror = true;
      setRotation(pang_ci3, 0F, 0F, 0F);  
      left_skirt = new ModelRenderer(this, 29, 57);
      left_skirt.addBox(-2F, 0F, -1F, 1, 5, 2);
      left_skirt.setRotationPoint(-3F, 7F, 1F);
      left_skirt.setTextureSize(256, 128);
      left_skirt.mirror = true;
      setRotation(left_skirt, 0F, 0F, 0F);
      left_side_skirt_1 = new ModelRenderer(this, 36, 57);
      left_side_skirt_1.addBox(-2F, 0F, -1F, 1, 4, 2);
      left_side_skirt_1.setRotationPoint(-3F, 7F, -1F);
      left_side_skirt_1.setTextureSize(256, 128);
      left_side_skirt_1.mirror = true;
      setRotation(left_side_skirt_1, 0F, 0F, 0F);
      left_side_skirt_2 = new ModelRenderer(this, 21, 57);
      left_side_skirt_2.addBox(-2F, 0F, -1F, 1, 4, 2);
      left_side_skirt_2.setRotationPoint(-3F, 7F, 3F);
      left_side_skirt_2.setTextureSize(256, 128);
      left_side_skirt_2.mirror = true;
      setRotation(left_side_skirt_2, 0F, 0F, 0F);
      right_skirt = new ModelRenderer(this, 29, 66);
      right_skirt.addBox(1F, 0F, -1F, 1, 5, 2);
      right_skirt.setRotationPoint(3F, 7F, 1F);
      right_skirt.setTextureSize(256, 128);
      right_skirt.mirror = true;
      setRotation(right_skirt, 0F, 0F, 0F);
      right_side_skirt_1 = new ModelRenderer(this, 21, 66);
      right_side_skirt_1.addBox(1F, 0F, -1F, 1, 4, 2);
      right_side_skirt_1.setRotationPoint(3F, 7F, -1F);
      right_side_skirt_1.setTextureSize(256, 128);
      right_side_skirt_1.mirror = true;
      setRotation(right_side_skirt_1, 0F, 0F, 0F);
      right_side_skirt_2 = new ModelRenderer(this, 37, 66);
      right_side_skirt_2.addBox(1F, 0F, -1F, 1, 4, 2);
      right_side_skirt_2.setRotationPoint(3F, 7F, 3F);
      right_side_skirt_2.setTextureSize(256, 128);
      right_side_skirt_2.mirror = true;
      setRotation(right_side_skirt_2, 0F, 0F, 0F);
      front_skirt = new ModelRenderer(this, 27, 22);
      front_skirt.addBox(-2F, 0F, -2F, 4, 5, 1);
      front_skirt.setRotationPoint(0F, 7F, 0F);
      front_skirt.setTextureSize(256, 128);
      front_skirt.mirror = true;
      setRotation(front_skirt, 0F, 0F, 0F);
      front_side_skirt1 = new ModelRenderer(this, 18, 22);
      front_side_skirt1.addBox(-2F, 0F, -2F, 2, 4, 1);
      front_side_skirt1.setRotationPoint(-2F, 7F, 0F);
      front_side_skirt1.setTextureSize(256, 128);
      front_side_skirt1.mirror = true;
      setRotation(front_side_skirt1, 0F, 0F, 0F);
      front_side_skirt_2 = new ModelRenderer(this, 39, 22);
      front_side_skirt_2.addBox(0F, -1F, -4F, 2, 4, 1);
      front_side_skirt_2.setRotationPoint(2F, 8F, 2F);
      front_side_skirt_2.setTextureSize(256, 128);
      front_side_skirt_2.mirror = true;
      setRotation(front_side_skirt_2, 0F, 0F, 0F);
      back_skirt = new ModelRenderer(this, 27, 30);
      back_skirt.addBox(-2F, 0F, 1F, 4, 5, 1);
      back_skirt.setRotationPoint(0F, 7F, 2F);
      back_skirt.setTextureSize(256, 128);
      back_skirt.mirror = true;
      setRotation(back_skirt, 0F, 0F, 0F);
      back_side_skirt1 = new ModelRenderer(this, 18, 30);
      back_side_skirt1.addBox(0F, 0F, 1F, 2, 4, 1);
      back_side_skirt1.setRotationPoint(2F, 7F, 2F);
      back_side_skirt1.setTextureSize(256, 128);
      back_side_skirt1.mirror = true;
      setRotation(back_side_skirt1, 0F, 0F, 0F);
      back_side_skirt2 = new ModelRenderer(this, 39, 30);
      back_side_skirt2.addBox(0F, 0F, 0F, 2, 4, 1);
      back_side_skirt2.setRotationPoint(-4F, 7F, 3F);
      back_side_skirt2.setTextureSize(256, 128);
      back_side_skirt2.mirror = true;
      setRotation(back_side_skirt2, 0F, 0F, 0F);
      left_sock_bottom = new ModelRenderer(this, 0, 86);
      left_sock_bottom.addBox(-4.5F, 5F, -1F, 1, 1, 1);
      left_sock_bottom.setRotationPoint(-1F, 9F, 1F);
      left_sock_bottom.setTextureSize(256, 128);
      left_sock_bottom.mirror = true;
      setRotation(left_sock_bottom, 0F, 0F, 0F);
      right_sock_bottom = new ModelRenderer(this, 0, 86);
      right_sock_bottom.addBox(3.5F, 5F, -1F, 1, 1, 1);
      right_sock_bottom.setRotationPoint(1F, 9F, 1F);
      right_sock_bottom.setTextureSize(256, 128);
      right_sock_bottom.mirror = true;
      setRotation(right_sock_bottom, 0F, 0F, 0F);
      clothes_right_bottom1 = new ModelRenderer(this, 0, 94);
      clothes_right_bottom1.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_right_bottom1.setRotationPoint(3.3F, -4.8F, -2.5F);
      clothes_right_bottom1.setTextureSize(256, 128);
      clothes_right_bottom1.mirror = true;
      setRotation(clothes_right_bottom1, 0F, 0F, 0F);
      clothes_right_bottom2 = new ModelRenderer(this, 0, 94);
      clothes_right_bottom2.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_right_bottom2.setRotationPoint(1.5F, -1F, -2.5F);
      clothes_right_bottom2.setTextureSize(256, 128);
      clothes_right_bottom2.mirror = true;
      setRotation(clothes_right_bottom2, 0F, 0F, 0F);
      clothes_right_bottom3 = new ModelRenderer(this, 0, 94);
      clothes_right_bottom3.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_right_bottom3.setRotationPoint(1.8F, 4.3F, -2.5F);
      clothes_right_bottom3.setTextureSize(256, 128);
      clothes_right_bottom3.mirror = true;
      setRotation(clothes_right_bottom3, 0F, 0F, 0F);
      clothes_right_bottom4 = new ModelRenderer(this, 0, 94);
      clothes_right_bottom4.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_right_bottom4.setRotationPoint(3.3F, 8F, -2.5F);
      clothes_right_bottom4.setTextureSize(256, 128);
      clothes_right_bottom4.mirror = true;
      setRotation(clothes_right_bottom4, 0F, 0F, 0F);
      clothes_left_bottom1 = new ModelRenderer(this, 0, 94);
      clothes_left_bottom1.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_left_bottom1.setRotationPoint(-4.5F, -4.8F, -2.5F);
      clothes_left_bottom1.setTextureSize(256, 128);
      clothes_left_bottom1.mirror = true;
      setRotation(clothes_left_bottom1, 0F, 0F, 0F);
      clothes_left_bottom2 = new ModelRenderer(this, 0, 94);
      clothes_left_bottom2.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_left_bottom2.setRotationPoint(-2.5F, -1F, -2.5F);
      clothes_left_bottom2.setTextureSize(256, 128);
      clothes_left_bottom2.mirror = true;
      setRotation(clothes_left_bottom2, 0F, 0F, 0F);
      clothes_left_bottom3 = new ModelRenderer(this, 0, 94);
      clothes_left_bottom3.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_left_bottom3.setRotationPoint(-2.8F, 4.3F, -2.5F);
      clothes_left_bottom3.setTextureSize(256, 128);
      clothes_left_bottom3.mirror = true;
      setRotation(clothes_left_bottom3, 0F, 0F, 0F);
      clothes_left_bottom4 = new ModelRenderer(this, 0, 94);
      clothes_left_bottom4.addBox(0F, 0F, 0F, 1, 1, 1);
      clothes_left_bottom4.setRotationPoint(-4.3F, 8F, -2.5F);
      clothes_left_bottom4.setTextureSize(256, 128);
      clothes_left_bottom4.mirror = true;
      setRotation(clothes_left_bottom4, 0F, 0F, 0F);
      left_hand_front_lace = new ModelRenderer(this, 63, 59);//
      left_hand_front_lace.addBox(-5F, 16F, -3F, 6, 2, 1);
      left_hand_front_lace.setRotationPoint(-5F, -6F, 1F);
      left_hand_front_lace.setTextureSize(256, 128);
      left_hand_front_lace.mirror = true;
      setRotation(left_hand_front_lace, 0F, 0F, 0F);
      left_hand_back_lace = new ModelRenderer(this, 63, 76);//
      left_hand_back_lace.addBox(-5F, 16F, 5F, 6, 2, 1);
      left_hand_back_lace.setRotationPoint(-5F, -6F, 1F);
      left_hand_back_lace.setTextureSize(256, 128);
      left_hand_back_lace.mirror = true;
      setRotation(left_hand_back_lace, 0F, 0F, 0F);
      left_hand_left_lace = new ModelRenderer(this, 73, 64);//
      left_hand_left_lace.addBox(-5F, 16F, -2F, 1, 2, 7);
      left_hand_left_lace.setRotationPoint(-5F, -6F, 1F);
      left_hand_left_lace.setTextureSize(256, 128);
      left_hand_left_lace.mirror = true;
      setRotation(left_hand_left_lace, 0F, 0F, 0F);
      lfet_hand_right_lace = new ModelRenderer(this, 55, 64);//
      lfet_hand_right_lace.addBox(0F, 16F, -2F, 1, 2, 7);
      lfet_hand_right_lace.setRotationPoint(-5F, -6F, 1F);
      lfet_hand_right_lace.setTextureSize(256, 128);
      lfet_hand_right_lace.mirror = true;
      setRotation(lfet_hand_right_lace, 0F, 0F, 0F);  
      right_hand_front_lace = new ModelRenderer(this, 102, 59);//
      right_hand_front_lace.addBox(-1F, 16F, -3F, 6, 2, 1);
      right_hand_front_lace.setRotationPoint(5F, -6F, 1F);
      right_hand_front_lace.setTextureSize(256, 128);
      right_hand_front_lace.mirror = true;
      setRotation(right_hand_front_lace, 0F, 0F, 0F);
      right_hand_back_lace = new ModelRenderer(this, 102, 75);//
      right_hand_back_lace.addBox(-1F, 16F, 5F, 6, 2, 1);
      right_hand_back_lace.setRotationPoint(5F, -6F, 1F);
      right_hand_back_lace.setTextureSize(256, 128);
      right_hand_back_lace.mirror = true;
      setRotation(right_hand_back_lace, 0F, 0F, 0F);
      right_hand_right_lace = new ModelRenderer(this, 110, 63);//
      right_hand_right_lace.addBox(4F, 16F, -2F, 1, 2, 7);
      right_hand_right_lace.setRotationPoint(5F, -6F, 1F);
      right_hand_right_lace.setTextureSize(256, 128);
      right_hand_right_lace.mirror = true;
      setRotation(right_hand_right_lace, 0F, 0F, 0F);
      right_hand_left_lace = new ModelRenderer(this, 92, 63);//
      right_hand_left_lace.addBox(-1F, 16F, -2F, 1, 2, 7);
      right_hand_left_lace.setRotationPoint(5F, -6F, 1F);
      right_hand_left_lace.setTextureSize(256, 128);
      right_hand_left_lace.mirror = true;
      setRotation(right_hand_left_lace, 0F, 0F, 0F);
      left_hand_front_fronter_lace1 = new ModelRenderer(this, 62, 83);//
      left_hand_front_fronter_lace1.addBox(-4F, 16F, -4F, 1, 2, 1);
      left_hand_front_fronter_lace1.setRotationPoint(-4.5F, -5.7F, 1.7F);
      left_hand_front_fronter_lace1.setTextureSize(256, 128);
      left_hand_front_fronter_lace1.mirror = true;
      setRotation(left_hand_front_fronter_lace1, 0F, 0F, 0F);
      left_hand_front_fronter_lace2 = new ModelRenderer(this, 62, 83);//
      left_hand_front_fronter_lace2.addBox(-2F, 16F, -3F, 1, 2, 1);
      left_hand_front_fronter_lace2.setRotationPoint(-4.5F, -5.7F, 0.7F);
      left_hand_front_fronter_lace2.setTextureSize(256, 128);
      left_hand_front_fronter_lace2.mirror = true;
      setRotation(left_hand_front_fronter_lace2, 0F, 0F, 0F);
      left_hand_front_fronter_lace3 = new ModelRenderer(this, 70, 83);//
      left_hand_front_fronter_lace3.addBox(0F, 16F, -3F, 1, 2, 1);
      left_hand_front_fronter_lace3.setRotationPoint(-4.7F, -5.7F, 0.7F);
      left_hand_front_fronter_lace3.setTextureSize(256, 128);
      left_hand_front_fronter_lace3.mirror = true;
      setRotation(left_hand_front_fronter_lace3, 0F, 0F, 0F);
      left_hand_right_fronter_lace1 = new ModelRenderer(this, 62, 97);//
      left_hand_right_fronter_lace1.addBox(0F, 16F, -1F, 1, 2, 1);
      left_hand_right_fronter_lace1.setRotationPoint(-4.7F, -5.7F, 0.7F);
      left_hand_right_fronter_lace1.setTextureSize(256, 128);
      left_hand_right_fronter_lace1.mirror = true;
      setRotation(left_hand_right_fronter_lace1, 0F, 0F, 0F);
      left_hand_right_fronter_lace2 = new ModelRenderer(this, 63, 97);//
      left_hand_right_fronter_lace2.addBox(0F, 16F, 1F, 1, 2, 1);
      left_hand_right_fronter_lace2.setRotationPoint(-4.7F, -5.7F, 0.8F);
      left_hand_right_fronter_lace2.setTextureSize(256, 128);
      left_hand_right_fronter_lace2.mirror = true;
      setRotation(left_hand_right_fronter_lace2, 0F, 0F, 0F);
      left_hand_right_fronter_lace3 = new ModelRenderer(this, 62, 97);//
      left_hand_right_fronter_lace3.addBox(0F, 16F, 4F, 1, 2, 1);
      left_hand_right_fronter_lace3.setRotationPoint(-4.7F, -5.7F, 0.3F);
      left_hand_right_fronter_lace3.setTextureSize(256, 128);
      left_hand_right_fronter_lace3.mirror = true;
      setRotation(left_hand_right_fronter_lace3, 0F, 0F, 0F);
      left_hand_right_fronter_lace4 = new ModelRenderer(this, 70, 97);//
      left_hand_right_fronter_lace4.addBox(0F, 16F, 6F, 1, 2, 1);
      left_hand_right_fronter_lace4.setRotationPoint(-4.7F, -5.7F, 0.3F);
      left_hand_right_fronter_lace4.setTextureSize(256, 128);
      left_hand_right_fronter_lace4.mirror = true;
      setRotation(left_hand_right_fronter_lace4, 0F, 0F, 0F);
      left_hand_back_fronter_lace1 = new ModelRenderer(this, 70, 90);//
      left_hand_back_fronter_lace1.addBox(-1.8F, 16F, 6F, 1, 2, 1);
      left_hand_back_fronter_lace1.setRotationPoint(-4.7F, -5.7F, 0.3F);
      left_hand_back_fronter_lace1.setTextureSize(256, 128);
      left_hand_back_fronter_lace1.mirror = true;
      setRotation(left_hand_back_fronter_lace1, 0F, 0F, 0F);
      left_hand_back_fronter_lace2 = new ModelRenderer(this, 70, 90);//
      left_hand_back_fronter_lace2.addBox(-3.8F, 16F, 6F, 1, 2, 1);
      left_hand_back_fronter_lace2.setRotationPoint(-4.7F, -5.7F, 0.3F);
      left_hand_back_fronter_lace2.setTextureSize(256, 128);
      left_hand_back_fronter_lace2.mirror = true;
      setRotation(left_hand_back_fronter_lace2, 0F, 0F, 0F);
      Left_hand_back_fronter_lace3 = new ModelRenderer(this, 55, 97);//
      Left_hand_back_fronter_lace3.addBox(-5F, 16F, 5F, 1, 2, 1);
      Left_hand_back_fronter_lace3.setRotationPoint(-5.3F, -5.7F, 1.3F);
      Left_hand_back_fronter_lace3.setTextureSize(256, 128);
      Left_hand_back_fronter_lace3.mirror = true;
      setRotation(Left_hand_back_fronter_lace3, 0F, 0F, 0F);
      left_hand_back_fronter_lace4 = new ModelRenderer(this, 55, 83);//
      left_hand_back_fronter_lace4.addBox(-6F, 16F, -3F, 1, 2, 1);
      left_hand_back_fronter_lace4.setRotationPoint(-4.3F, -5.7F, 0.7F);
      left_hand_back_fronter_lace4.setTextureSize(256, 128);
      left_hand_back_fronter_lace4.mirror = true;
      setRotation(left_hand_back_fronter_lace4, 0F, 0F, 0F);
      Left_hand_left_fronter_lace1 = new ModelRenderer(this, 55, 90);//
      Left_hand_left_fronter_lace1.addBox(-5F, 16F, 3F, 1, 2, 1);
      Left_hand_left_fronter_lace1.setRotationPoint(-5.3F, -5.7F, 1F);
      Left_hand_left_fronter_lace1.setTextureSize(256, 128);
      Left_hand_left_fronter_lace1.mirror = true;
      setRotation(Left_hand_left_fronter_lace1, 0F, 0F, 0F);
      left_hand_left_fronter_lace2 = new ModelRenderer(this, 55, 90);//
      left_hand_left_fronter_lace2.addBox(-5F, 16F, 1F, 1, 2, 1);
      left_hand_left_fronter_lace2.setRotationPoint(-5.3F, -5.7F, 1F);
      left_hand_left_fronter_lace2.setTextureSize(256, 128);
      left_hand_left_fronter_lace2.mirror = true;
      setRotation(left_hand_left_fronter_lace2, 0F, 0F, 0F);
      left_hand_left_fronter_lace3 = new ModelRenderer(this, 55, 90);//
      left_hand_left_fronter_lace3.addBox(-5F, 16F, -1F, 1, 2, 1);
      left_hand_left_fronter_lace3.setRotationPoint(-5.3F, -5.7F, 1F);
      left_hand_left_fronter_lace3.setTextureSize(256, 128);
      left_hand_left_fronter_lace3.mirror = true;
      setRotation(left_hand_left_fronter_lace3, 0F, 0F, 0F);
      upper_left_arm = new ModelRenderer(this, 63, 109);//
      upper_left_arm.addBox(-3F, -1F, -1F, 2, 5, 2);
      upper_left_arm.setRotationPoint(-5F, -6F, 1F);
      upper_left_arm.setTextureSize(256, 128);
      upper_left_arm.mirror = true;
      setRotation(upper_left_arm, 0F, 0F, 0F);
      left_arm_long_sleeve_front = new ModelRenderer(this, 63, 117);//
      left_arm_long_sleeve_front.addBox(-4F, 2F, -2F, 3, 2, 1);
      left_arm_long_sleeve_front.setRotationPoint(-5F, -6F, 1F);
      left_arm_long_sleeve_front.setTextureSize(256, 128);
      left_arm_long_sleeve_front.mirror = true;
      setRotation(left_arm_long_sleeve_front, 0F, 0F, 0F);
      Left_arm_long_sleeve_bottom = new ModelRenderer(this, 60, 122);//
      Left_arm_long_sleeve_bottom.addBox(-4F, 4F, -2F, 3, 1, 4);
      Left_arm_long_sleeve_bottom.setRotationPoint(-5F, -6F, 1F);
      Left_arm_long_sleeve_bottom.setTextureSize(256, 128);
      Left_arm_long_sleeve_bottom.mirror = true;
      setRotation(Left_arm_long_sleeve_bottom, 0F, 0F, 0F);
      left_arm_long_sleeve_left = new ModelRenderer(this, 54, 116);//
      left_arm_long_sleeve_left.addBox(-4F, 2F, -1F, 1, 2, 2);
      left_arm_long_sleeve_left.setRotationPoint(-5F, -6F, 1F);
      left_arm_long_sleeve_left.setTextureSize(256, 128);
      left_arm_long_sleeve_left.mirror = true;
      setRotation(left_arm_long_sleeve_left, 0F, 0F, 0F);
      left_arm_long_sleeve_back = new ModelRenderer(this, 63, 117);//
      left_arm_long_sleeve_back.addBox(-4F, 2F, 1F, 3, 2, 1);
      left_arm_long_sleeve_back.setRotationPoint(-5F, -6F, 1F);
      left_arm_long_sleeve_back.setTextureSize(256, 128);
      left_arm_long_sleeve_back.mirror = true;
      setRotation(left_arm_long_sleeve_back, 0F, 0F, 0F);
      
      left_arm.addChild(upper_left_arm);
      left_arm.addChild(left_arm_long_sleeve_front);
      left_arm.addChild(Left_arm_long_sleeve_bottom);
      left_arm.addChild(left_arm_long_sleeve_left);
      left_arm.addChild(left_arm_long_sleeve_back);
      left_arm.addChild(left_sleeve);
      left_arm.addChild(outter_left_sleeve);
      left_arm.addChild(outtest_left_sleeve);
      left_arm.addChild(outtest_left_sleeve);
      left_arm.addChild(left_hand_front_fronter_lace1);
      left_arm.addChild(left_hand_front_fronter_lace2);
      left_arm.addChild(left_hand_front_fronter_lace3);
      left_arm.addChild(left_hand_right_fronter_lace1);
      left_arm.addChild(left_hand_right_fronter_lace2);
      left_arm.addChild(left_hand_right_fronter_lace3);
      left_arm.addChild(left_hand_right_fronter_lace4);
      left_arm.addChild(left_hand_back_fronter_lace1);
      left_arm.addChild(left_hand_back_fronter_lace2);
      left_arm.addChild(Left_hand_back_fronter_lace3);
      left_arm.addChild(left_hand_back_fronter_lace4);
      left_arm.addChild(Left_hand_left_fronter_lace1);
      left_arm.addChild(left_hand_left_fronter_lace2);
      left_arm.addChild(left_hand_left_fronter_lace3);
      left_arm.addChild(left_hand_front_lace);
      left_arm.addChild(left_hand_back_lace);
      left_arm.addChild(left_hand_left_lace);
      left_arm.addChild(lfet_hand_right_lace);
      
      right_arm.addChild(right_sleeve);
      right_arm.addChild(outter_right_sleeve);
      right_arm.addChild(outtest_right_sleeve);
      right_arm.addChild(right_hand_front_lace);
      right_arm.addChild(right_hand_back_lace);
      right_arm.addChild(right_hand_right_lace);
      right_arm.addChild(right_hand_left_lace);
      right_arm.addChild(right_hand_front_fronter_lace1);
      right_arm.addChild(right_hand_front_fronter_lace2);
      right_arm.addChild(right_hand_front_fronter_lace3);
      right_arm.addChild(right_hand_front_fronter_lace4);
      right_arm.addChild(right_hand_right_fronter_lace1);
      right_arm.addChild(right_hand_right_fronter_lace2);
      right_arm.addChild(right_hand_right_fronter_lace3);
      right_arm.addChild(right_hand_right_fronter_lace4);
      right_arm.addChild(right_hand_back_fronter_lace1);
      right_arm.addChild(right_hand_back_fronter_lace2);
      right_arm.addChild(right_hand_back_fronter_lace3);
      right_arm.addChild(right_hand_left_fronter_lace1);
      right_arm.addChild(right_hand_left_fronter_lace2);
      right_arm.addChild(right_hand_left_fronter_lace3);
      right_arm.addChild(upper_right_arm_);
      right_arm.addChild(right_arm_long_sleeve_front);
      right_arm.addChild(right_arm_long_sleeve_bottom);
      right_arm.addChild(right_arm_long_sleeve_left);
      right_arm.addChild(right_arm_long_sleeve_back);
   
      upper_right_arm_ = new ModelRenderer(this, 63, 109);//
      upper_right_arm_.addBox(1F, -1F, -1F, 2, 5, 2);
      upper_right_arm_.setRotationPoint(5F, -6F, 1F);
      upper_right_arm_.setTextureSize(256, 128);
      upper_right_arm_.mirror = true;
      setRotation(upper_right_arm_, 0F, 0F, 0F);
      right_arm_long_sleeve_front = new ModelRenderer(this, 63, 117);//
      right_arm_long_sleeve_front.addBox(1F, 2F, -2F, 3, 2, 1);
      right_arm_long_sleeve_front.setRotationPoint(5F, -6F, 1F);
      right_arm_long_sleeve_front.setTextureSize(256, 128);
      right_arm_long_sleeve_front.mirror = true;
      setRotation(right_arm_long_sleeve_front, 0F, 0F, 0F);
      right_arm_long_sleeve_bottom = new ModelRenderer(this, 60, 122);//
      right_arm_long_sleeve_bottom.addBox(1F, 4F, -2F, 3, 1, 4);
      right_arm_long_sleeve_bottom.setRotationPoint(5F, -6F, 1F);
      right_arm_long_sleeve_bottom.setTextureSize(256, 128);
      right_arm_long_sleeve_bottom.mirror = true;
      setRotation(right_arm_long_sleeve_bottom, 0F, 0F, 0F);
      right_arm_long_sleeve_left = new ModelRenderer(this, 54, 116);//
      right_arm_long_sleeve_left.addBox(3F, 2F, -1F, 1, 2, 2);
      right_arm_long_sleeve_left.setRotationPoint(5F, -6F, 1F);
      right_arm_long_sleeve_left.setTextureSize(256, 128);
      right_arm_long_sleeve_left.mirror = true;
      setRotation(right_arm_long_sleeve_left, 0F, 0F, 0F);
      right_arm_long_sleeve_back = new ModelRenderer(this, 63, 117);//
      right_arm_long_sleeve_back.addBox(1F, 2F, 1F, 3, 2, 1);
      right_arm_long_sleeve_back.setRotationPoint(5F, -6F, 1F);
      right_arm_long_sleeve_back.setTextureSize(256, 128);
      right_arm_long_sleeve_back.mirror = true;
      setRotation(right_arm_long_sleeve_back, 0F, 0F, 0F);
      right_hand_front_fronter_lace1 = new ModelRenderer(this, 93, 83);//
      right_hand_front_fronter_lace1.addBox(-1F, 16F, -3F, 1, 2, 1);
      right_hand_front_fronter_lace1.setRotationPoint(4.8F, -5.7F, 0.7F);
      right_hand_front_fronter_lace1.setTextureSize(256, 128);
      right_hand_front_fronter_lace1.mirror = true;
      setRotation(right_hand_front_fronter_lace1, 0F, 0F, 0F);
      right_hand_front_fronter_lace2 = new ModelRenderer(this, 105, 83);//
      right_hand_front_fronter_lace2.addBox(0.8F, 16F, -3F, 1, 2, 1);
      right_hand_front_fronter_lace2.setRotationPoint(4.8F, -5.7F, 0.7F);
      right_hand_front_fronter_lace2.setTextureSize(256, 128);
      right_hand_front_fronter_lace2.mirror = true;
      setRotation(right_hand_front_fronter_lace2, 0F, 0F, 0F);
      right_hand_front_fronter_lace3 = new ModelRenderer(this, 105, 83);//
      right_hand_front_fronter_lace3.addBox(2.8F, 16F, -3F, 1, 2, 1);
      right_hand_front_fronter_lace3.setRotationPoint(4.8F, -5.7F, 0.7F);
      right_hand_front_fronter_lace3.setTextureSize(256, 128);
      right_hand_front_fronter_lace3.mirror = true;
      setRotation(right_hand_front_fronter_lace3, 0F, 0F, 0F);
      right_hand_front_fronter_lace4 = new ModelRenderer(this, 116, 83);//
      right_hand_front_fronter_lace4.addBox(4.3F, 16F, -3F, 1, 2, 1);
      right_hand_front_fronter_lace4.setRotationPoint(5F, -5.7F, 0.7F);
      right_hand_front_fronter_lace4.setTextureSize(256, 128);
      right_hand_front_fronter_lace4.mirror = true;
      setRotation(right_hand_front_fronter_lace4, 0F, 0F, 0F);
      right_hand_right_fronter_lace1 = new ModelRenderer(this, 116, 91);//
      right_hand_right_fronter_lace1.addBox(4.3F, 16F, -1F, 1, 2, 1);
      right_hand_right_fronter_lace1.setRotationPoint(5F, -5.7F, 1F);
      right_hand_right_fronter_lace1.setTextureSize(256, 128);
      right_hand_right_fronter_lace1.mirror = true;
      setRotation(right_hand_right_fronter_lace1, 0F, 0F, 0F);
      right_hand_right_fronter_lace2 = new ModelRenderer(this, 116, 91);//
      right_hand_right_fronter_lace2.addBox(4.3F, 16F, 1F, 1, 2, 1);
      right_hand_right_fronter_lace2.setRotationPoint(5F, -5.7F, 1F);
      right_hand_right_fronter_lace2.setTextureSize(256, 128);
      right_hand_right_fronter_lace2.mirror = true;
      setRotation(right_hand_right_fronter_lace2, 0F, 0F, 0F);
      right_hand_right_fronter_lace3 = new ModelRenderer(this, 116, 91);//
      right_hand_right_fronter_lace3.addBox(4.3F, 16F, 3.3F, 1, 2, 1);
      right_hand_right_fronter_lace3.setRotationPoint(5F, -5.7F, 0.6733333F);
      right_hand_right_fronter_lace3.setTextureSize(256, 128);
      right_hand_right_fronter_lace3.mirror = true;
      setRotation(right_hand_right_fronter_lace3, 0F, 0F, 0F);
      right_hand_right_fronter_lace4 = new ModelRenderer(this, 116, 100);//
      right_hand_right_fronter_lace4.addBox(4F, 16F, 5.7F, 1, 2, 1);
      right_hand_right_fronter_lace4.setRotationPoint(5.3F, -5.7F, 0.7F);
      right_hand_right_fronter_lace4.setTextureSize(256, 128);
      right_hand_right_fronter_lace4.mirror = true;
      setRotation(right_hand_right_fronter_lace4, 0F, 0F, 0F);
      right_hand_back_fronter_lace1 = new ModelRenderer(this, 105, 100);//
      right_hand_back_fronter_lace1.addBox(2.3F, 16F, 5.7F, 1, 2, 1);
      right_hand_back_fronter_lace1.setRotationPoint(5.2F, -5.7F, 0.7F);
      right_hand_back_fronter_lace1.setTextureSize(256, 128);
      right_hand_back_fronter_lace1.mirror = true;
      setRotation(right_hand_back_fronter_lace1, 0F, 0F, 0F);
      right_hand_back_fronter_lace2 = new ModelRenderer(this, 105, 100);//
      right_hand_back_fronter_lace2.addBox(0.5F, 16F, 5.3F, 1, 2, 1);
      right_hand_back_fronter_lace2.setRotationPoint(5F, -5.7F, 1F);
      right_hand_back_fronter_lace2.setTextureSize(256, 128);
      right_hand_back_fronter_lace2.mirror = true;
      setRotation(right_hand_back_fronter_lace2, 0F, 0F, 0F);
      right_hand_back_fronter_lace3 = new ModelRenderer(this, 93, 100);//
      right_hand_back_fronter_lace3.addBox(-1F, 16F, 5F, 1, 2, 1);
      right_hand_back_fronter_lace3.setRotationPoint(4.7F, -5.7F, 1.3F);
      right_hand_back_fronter_lace3.setTextureSize(256, 128);
      right_hand_back_fronter_lace3.mirror = true;
      setRotation(right_hand_back_fronter_lace3, 0F, 0F, 0F);
      right_hand_left_fronter_lace1 = new ModelRenderer(this, 93, 91);//
      right_hand_left_fronter_lace1.addBox(-1F, 16F, 3F, 1, 2, 1);
      right_hand_left_fronter_lace1.setRotationPoint(4.7F, -5.7F, 1F);
      right_hand_left_fronter_lace1.setTextureSize(256, 128);
      right_hand_left_fronter_lace1.mirror = true;
      setRotation(right_hand_left_fronter_lace1, 0F, 0F, 0F);
      right_hand_left_fronter_lace2 = new ModelRenderer(this, 93, 91);//
      right_hand_left_fronter_lace2.addBox(-1F, 16F, 0F, 1, 2, 1);
      right_hand_left_fronter_lace2.setRotationPoint(4.7F, -5.7F, 2F);
      right_hand_left_fronter_lace2.setTextureSize(256, 128);
      right_hand_left_fronter_lace2.mirror = true;
      setRotation(right_hand_left_fronter_lace2, 0F, 0F, 0F);
      right_hand_left_fronter_lace3 = new ModelRenderer(this, 93, 91);//
      right_hand_left_fronter_lace3.addBox(-1F, 16F, 0F, 1, 2, 1);
      right_hand_left_fronter_lace3.setRotationPoint(4.7F, -5.7F, 0F);
      right_hand_left_fronter_lace3.setTextureSize(256, 128);
      right_hand_left_fronter_lace3.mirror = true;
      setRotation(right_hand_left_fronter_lace3, 0F, 0F, 0F);


  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Left_Leg.render(f5);
    Right_Leg.render(f5);
    left_Leg_sock_left.render(f5);
    Left_Leg_sock_right.render(f5);
    Left_Leg_sock_Front.render(f5);
    Left_Leg_sock_back.render(f5);
    Right_Leg_sock_left.render(f5);
    Right_Leg_sock_right.render(f5);
    Right_Leg_sock_front.render(f5);
    Right_Leg_sock_back.render(f5);
    Body.render(f5);
    neck.render(f5);
    collar_left.render(f5);
    collar_right.render(f5);
    collar_back.render(f5);
    head.render(f5);
    left_hair.render(f5);
    right_hair.render(f5);
    Front_hair.render(f5);
    Front_hair_medium.render(f5);
    Front_hair_right.render(f5);
    back_hair.render(f5);
    top_hair.render(f5);
    front_hair1.render(f5);
    front_hair_2.render(f5);
    front_hair3.render(f5);
    front_hair_4.render(f5);
    front_hair5.render(f5);
    front_hair6.render(f5);
    front_hair7.render(f5);
    outer_left_hair.render(f5);
    outer_right_hair.render(f5);
    back_hair1.render(f5);
    back_hair2.render(f5);
    back_hair3.render(f5);
    back_hair4.render(f5);
    back_hair5.render(f5);
    left_arm.render(f5);
    right_arm.render(f5);
    left_sleeve.render(f5);
    outter_left_sleeve.render(f5);
    outtest_left_sleeve.render(f5);
    right_sleeve.render(f5);
    outter_right_sleeve.render(f5);
    outtest_right_sleeve.render(f5);
    tie1.render(f5);
    tie3.render(f5);
    tie4.render(f5);
    tie5.render(f5);
    pang_ci1.render(f5);
    pang_ci2.render(f5);
    pang_ci3.render(f5);
    left_skirt.render(f5);
    left_side_skirt_1.render(f5);
    left_side_skirt_2.render(f5);
    right_skirt.render(f5);
    right_side_skirt_1.render(f5);
    right_side_skirt_2.render(f5);
    front_skirt.render(f5);
    front_side_skirt1.render(f5);
    front_side_skirt_2.render(f5);
    back_skirt.render(f5);
    back_side_skirt1.render(f5);
    back_side_skirt2.render(f5);
    left_sock_bottom.render(f5);
    right_sock_bottom.render(f5);
    clothes_right_bottom1.render(f5);
    clothes_right_bottom2.render(f5);
    clothes_right_bottom3.render(f5);
    clothes_right_bottom4.render(f5);
    clothes_left_bottom1.render(f5);
    clothes_left_bottom2.render(f5);
    clothes_left_bottom3.render(f5);
    clothes_left_bottom4.render(f5);
    left_hand_front_lace.render(f5);
    left_hand_back_lace.render(f5);
    left_hand_left_lace.render(f5);
    lfet_hand_right_lace.render(f5);
    right_hand_front_lace.render(f5);
    right_hand_back_lace.render(f5);
    right_hand_right_lace.render(f5);
    right_hand_left_lace.render(f5);
    left_hand_front_fronter_lace1.render(f5);
    left_hand_front_fronter_lace2.render(f5);
    left_hand_front_fronter_lace3.render(f5);
    left_hand_right_fronter_lace1.render(f5);
    left_hand_right_fronter_lace2.render(f5);
    left_hand_right_fronter_lace3.render(f5);
    left_hand_right_fronter_lace4.render(f5);
    left_hand_back_fronter_lace1.render(f5);
    left_hand_back_fronter_lace2.render(f5);
    Left_hand_back_fronter_lace3.render(f5);
    left_hand_back_fronter_lace4.render(f5);
    Left_hand_left_fronter_lace1.render(f5);
    left_hand_left_fronter_lace2.render(f5);
    left_hand_left_fronter_lace3.render(f5);
    right_hand_front_fronter_lace1.render(f5);
    right_hand_front_fronter_lace2.render(f5);
    right_hand_front_fronter_lace3.render(f5);
    right_hand_front_fronter_lace4.render(f5);
    right_hand_right_fronter_lace1.render(f5);
    right_hand_right_fronter_lace2.render(f5);
    right_hand_right_fronter_lace3.render(f5);
    right_hand_right_fronter_lace4.render(f5);
    right_hand_back_fronter_lace1.render(f5);
    right_hand_back_fronter_lace2.render(f5);
    right_hand_back_fronter_lace3.render(f5);
    right_hand_left_fronter_lace1.render(f5);
    right_hand_left_fronter_lace2.render(f5);
    right_hand_left_fronter_lace3.render(f5);
    outer_left_hair1.render(f5);
    outer_left_hair2.render(f5);
    outer_left_hair3.render(f5);
    outer_left_hair4.render(f5);
    outer_right_hair1.render(f5);
    outer_right_hair2.render(f5);
    outer_right_hair3.render(f5);
    outer_right_hair4.render(f5);
    upper_left_arm.render(f5);
    left_arm_long_sleeve_front.render(f5);
    Left_arm_long_sleeve_bottom.render(f5);
    left_arm_long_sleeve_left.render(f5);
    left_arm_long_sleeve_back.render(f5);
    upper_right_arm_.render(f5);
    right_arm_long_sleeve_front.render(f5);
    right_arm_long_sleeve_bottom.render(f5);
    right_arm_long_sleeve_left.render(f5);
    right_arm_long_sleeve_back.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par7)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, par7);
  }

}
